name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies and render static files
        run: |
          pip install -r requirements.txt
          python render.py

      - uses: actions/deploy-pages@v4
        with:
          publish-dir: ./renders
