name: Create Release Zip

on:
  release:
    types:
      [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies and render static files
        run: |
          pip install -r requirements.txt
          python render.py

      - name: Zip rendered output
        run: zip -r social-stack.zip renders/

      - name: Upload zip to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: social-stack.zip
